(
    (rules
        ((and @x @x) @x)
        ((or @x @x) @x)
        ((and (not @x) (not @y)) (not (or @x @y)))
        ((or (not @x) (not @y)) (not (and @x @y)))
        ((and (and @x @y) @z) (and @x (and @y @z)))
        ((or (or @x @y) @z) (or @x (or @y @z)))
        ((or true @x) true)
        ((or @x true) true)
        ((or false @x) @x)
        ((or @x false) @x)
        ((not true) false)
        ((not (not @x)) @x)
        ((not false) true)
        ((and @x true) @x)
        ((and true @x) @x)
        ((and @x false) false)
        ((and false @x) false)
    )
    (eqs
        ((and @x @y) (and @y @x))
        ((or @x @y) (or @y @x))
        ((and @x (and @y @z)) (and @z (and @x @y)))
        ((or @x (or @y @z)) (or @z (or @x @y)))
    )
    (weights
        (and 1)
        (or 2)
        (not 3)
    )
    (precs
        (and 1)
        (or 2)
        (not 3)
    )
)
