(
    (rules
        ((lt @x @x) false)
        ((gt @x @x) false)
        ((leq @x @x) true)
        ((geq @x @x) true)
        ((neq @x @x) false)
        ((eq @x @x) true)
        ((not (lt @x @y)) (geq @x @y))
        ((not (gt @x @y)) (leq @x @y))
        ((not (eq @x @y)) (neq @x @y))
        ((not (neq @x @y)) (eq @x @y))
        ((and (leq @x @y) (eq @x @y)) (leq @x @y))
        ((and (leq @x @y) (lt @x @y)) (lt @x @y))
        ((and (geq @x @y) (eq @x @y)) (geq @x @y))
        ((and (geq @x @y) (gt @x @y)) (gt @x @y))
        ((or (geq @x @y) (lt @x @y)) true)
        ((and (geq @x @y) (lt @x @y)) false)
        ((or (leq @x @y) (gt @x @y)) true)
        ((and (leq @x @y) (gt @x @y)) false)
    )
    (eqs
        ((eq @x @y) (eq @y @x))
        ((neq @x @y) (neq @y @x))
    )
    (weights
        (lt 1)
        (gt 2)
        (leq 3)
        (geq 4)
        (neq 5)
        (eq 6)
    )
    (precs
        (lt 1)
        (gt 2)
        (leq 3)
        (geq 4)
        (neq 5)
        (eq 6)
    )
)
