(
    (rules
        ((join (split @x @y) @y) @x)
        ((to_upper (to_upper @x)) (to_upper @x))
        ((to_lower (to_lower @x)) (to_lower @x))
        ((trim (trim @x)) (trim @x))
        ((add (length @x) (length @y)) (length (concat @x @y)))
        ((concat (to_upper @x) (to_upper @y)) (to_upper (concat @x @y)))
        ((concat (to_lower @x) (to_lower @y)) (to_lower (concat @x @y)))
        ((reverse (reverse @x)) @x)
        ((length (reverse @x)) (length @x))
        ((length (to_upper @x)) (length @x))
        ((length (to_lower @x)) (length @x))
        ((trim (reverse @x)) (reverse (trim @x)))
        ((to_upper (reverse @x)) (reverse (to_upper @x)))
        ((to_lower (reverse @x)) (reverse (to_lower @x)))
        ((to_int (of_int @x)) @x)
        ((of_int (to_int @x)) @x)
        ((to_int (to_lower @x)) (to_int @x))
        ((to_int (to_upper @x)) (to_upper @x))
    )
)
